name: nightly
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build-linux:
    if: ${{ endsWith(github.repository, 'winetest') && false }}
    uses: ./.github/workflows/build-linux.yml
    with:
      commit: master

  build-macos:
    if: ${{ endsWith(github.repository, 'winetest') && false }}
    uses: ./.github/workflows/build-macos.yml
    with:
      commit: master

  tests-linux:
    if: ${{ endsWith(github.repository, 'winetest') && false }}
    needs: build-linux
    uses: ./.github/workflows/tests-linux.yml
    with:
      event: ${{ github.event_name }}

  tests-macos:
    if: ${{ endsWith(github.repository, 'winetest') && false }}
    needs: build-macos
    uses: ./.github/workflows/tests-macos.yml
    with:
      event: ${{ github.event_name }}

  tests-windows:
    if: ${{ endsWith(github.repository, 'winetest') }}
    uses: ./.github/workflows/start-windows.yml
    secrets: inherit
    with:
      event: ${{ github.event_name }}
      run_id: ${{ github.run_id }}

  clean:
    needs: [tests-linux, tests-macos, tests-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
